// Generated by CoffeeScript 1.9.2
(function() {
  var React, React3, Simple, THREE;

  React = require('react');

  React3 = require('react-three-renderer');

  THREE = require('three');

  Simple = React.createClass({
    displayName: 'Simple',
    getInitialState: function() {
      return this.state = {
        cameraPosition: new THREE.Vector3(0, 0, 5),
        cubeRotation: new THREE.Euler()
      };
    },
    onAnimate: function() {
      return this.setState({
        cubeRotation: new THREE.Euler(this.state.cubeRotation.x + 0.1, this.state.cubeRotation.y + 0.1, 0)
      });
    },
    render: function() {
      var height, width;
      width = window.innerWidth;
      height = window.innerHeight;
      return React.createElement(React3, {
        "mainCamera": "camera",
        "width": width,
        "height": height,
        "onAnimate": this.onAnimate
      }, React.createElement("scene", null, React.createElement("perspectiveCamera", {
        "name": "camera",
        "fov": 75.,
        "aspect": width / height,
        "near": 0.1,
        "far": 1000.,
        "position": this.state.cameraPosition
      }), React.createElement("mesh", {
        "rotation": this.state.cubeRotation
      }, React.createElement("boxGeometry", {
        "width": 1.,
        "height": 1.,
        "depth": 1.
      }), React.createElement("meshBasicMaterial", {
        "color": 0x00ff00
      }))));
    }
  });

  exports.view = function() {
    return React.createElement(Simple, null);
  };

}).call(this);
